### ISSUE TITLE
Application suitability

### ISSUE THREAD

**Issue by teyiatia** [rivasiker/autocoalhmm#1]
Could this program be used for data within a species，or between populations?

**Comment by rivasiker** [comment]
You could potentially apply it to within-species samples, although it might much trickier due to the presence of other phenomena such as introgression or hybridization that might obscure the signal. You might also want to check our [new preprint](https://www.biorxiv.org/content/10.1101/2023.06.22.546039v2), in which we describe an improved version of CoalHMM.

**Comment by teyiatia** [comment]
thanks a lot!
